[package]
name = "shelby"
version = "1.3.2"
authors = ["Maciej MaÅ‚ecki <me@mmalecki.com>"]

[dependencies]
timer = "0.1.6"
rustc-serialize = "0.3.21"
numbat = "1.0.0"
chrono = "0.2.25"
serde_json = "0.8.3"
libc = "0.2.20"
linux-stats = "0.2.0"
